environment:
  matrix:
  - PYTHON: "C:\\Python27-x64"
    TARGET: x86_64-pc-windows-msvc
  - PYTHON: "C:\\Python36-x64"
    TARGET: x86_64-pc-windows-msvc
  - PYTHON: "C:\\Python37-x64"
    TARGET: x86_64-pc-windows-msvc

branches:
  only:
    - master
    - develop
    - /lts-.*/

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V
  - ps: (Get-Content python/snips_nlu_utils_py/Cargo.toml) | ForEach-Object { $_ -replace "^snips-nlu-utils = .*$", "snips-nlu-utils = { path = `"../..`" }" } | Set-Content python/snips_nlu_utils_py/Cargo.toml
  - "%PYTHON%\\python.exe -m pip install -r python/requirements.txt"

build: false

test_script:
  - cargo test --verbose
  - cd python
  - "%PYTHON%\\python.exe -m pip install -e . --verbose"
  - "%PYTHON%\\python.exe -m unittest discover"

after_test:
  - ECHO "BUILDING WHEELS..."
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: python\dist\*
    name: pypiartifacts

for:
-
  branches:
    only:
      - master
      - /lts-.*/

  environment:
    matrix:
    - PYTHON: "C:\\Python27"
      TARGET: i686-pc-windows-msvc
    - PYTHON: "C:\\Python36"
      TARGET: i686-pc-windows-msvc
    - PYTHON: "C:\\Python37"
      TARGET: i686-pc-windows-msvc
