matrix:
  include:
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - os: osx
      osx_image: xcode8
      language: generic
      env:
      - TOXENV=py37
      - PYTHON_TESTS=true
    - os: osx
      osx_image: xcode8
      language: generic
      env:
      - TOXENV=py38
      - PYTHON_TESTS=true
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON_TESTS=true
    - os: linux
      language: python
      python: 3.7
      # cf https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true
      env:
      - TOXENV=py37
      - PYTHON_TESTS=true
    - os: linux
      language: python
      python: 3.8
      # cf https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true
      env:
      - TOXENV=py37
      - PYTHON_TESTS=true
    - os: linux
      language: rust
      rust: stable
      env:
        - RUST_TESTS=true

before_install: . ./.travis/before_install.sh

script: ./.travis/test.sh
